/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import bean.JceClientes;
import bean.JceVendas;
import bean.JcePublicadoras;
import bean.JceHqs;
import bean.JceVendasProdutos;
import dao.ClientesDAO;
import dao.PublicadorasDAO;
import dao.HQsDAO;
import dao.VendasDAO;
import dao.VendasProdutosDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import viewControllers.ControllerVendasProdutos;
import java.util.ArrayList;
import javax.swing.JTable;
import viewPesquisas.JDlgVendasPesquisar;
import tools.Util;

/**
 *
 * @author Caio
 */
public class JDlgVendas extends javax.swing.JDialog {

    private MaskFormatter mascaraData;
    ControllerVendasProdutos controllerVendasProdutos;
    boolean incluir;
    /**
     * Creates new form JDlgVendas
     */
    
    public JDlgVendas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Vendas");
        setLocationRelativeTo(null);
        
        try {
            mascaraData = new MaskFormatter("##/##/####");
            
            jFmtData.setFormatterFactory(new DefaultFormatterFactory(mascaraData));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Util.habilitar(false, jTxtCodigo, jFmtData, jCboClientes,  jCboPublicadoras, jFmtTotal, jBtnIncluir2,  jBtnAlterar2,  jBtnExcluir2, jBtnConfirmar,jBtnCancelar, jBtnExcluir);
        Util.habilitar(true,jBtnIncluir, jBtnAlterar);
                
        
                ClientesDAO clientesDAO = new ClientesDAO();
        List lista = (List) clientesDAO.listAll();
        for (int i = 0; i < lista.size(); i++) {
            jCboClientes.addItem((JceClientes) lista.get(i));
        }
        
        
        PublicadorasDAO publicadorasDAO = new PublicadorasDAO();
        List listaVend = (List) publicadorasDAO.listAll();
        for (Object object : listaVend) {
            jCboPublicadoras.addItem((JcePublicadoras) object);
        }
        
        controllerVendasProdutos = new ControllerVendasProdutos();
        controllerVendasProdutos.setList(new ArrayList());
        jTable1.setModel(controllerVendasProdutos);
    }
    
    public JceVendas viewBean() {
        JceVendas jceVendas = new JceVendas();
        jceVendas.setJceIdvendas(Integer.valueOf(jTxtCodigo.getText()));
        jceVendas.setJceData(Util.strToDate(jFmtData.getText()));
        jceVendas.setJceTotal(Double.valueOf(jFmtTotal.getText()));
        jceVendas.setJceClientes((JceClientes)jCboClientes.getSelectedItem());
        jceVendas.setJcePublicadoras((JcePublicadoras)jCboPublicadoras.getSelectedItem());
        
         return jceVendas;
    }
    
    public void beanView(JceVendas jceVendas, List lista){
        jTxtCodigo.setText(Util.intToStr(jceVendas.getJceIdvendas()));
        jFmtData.setText(Util.dateToStr(jceVendas.getJceData()));
        jFmtTotal.setText(Util.doubleToStr(jceVendas.getJceTotal()));
        jCboClientes.setSelectedItem(jceVendas.getJceClientes());
        jCboClientes.setSelectedItem(jceVendas.getJceIdvendas());
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        lista = (List) vendasProdutosDAO.listProdutos(jceVendas);
        controllerVendasProdutos.setList(lista);
    }
    
    public JTable getjTable1() {
        return jTable1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnExcluir2 = new javax.swing.JButton();
        jBtnAlterar2 = new javax.swing.JButton();
        jBtnIncluir2 = new javax.swing.JButton();
        jFmtTotal = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jCboPublicadoras = new javax.swing.JComboBox<JcePublicadoras>();
        jLabel4 = new javax.swing.JLabel();
        jCboClientes = new javax.swing.JComboBox<JceClientes>();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnIncluir = new javax.swing.JButton();
        jFmtData = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBtnExcluir2.setBackground(new java.awt.Color(0, 0, 0));
        jBtnExcluir2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixo2.png"))); // NOI18N

        jBtnAlterar2.setBackground(new java.awt.Color(0, 0, 0));
        jBtnAlterar2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapis2.png"))); // NOI18N

        jBtnIncluir2.setBackground(new java.awt.Color(0, 0, 0));
        jBtnIncluir2.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIncluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/download2.png"))); // NOI18N

        jFmtTotal.setBackground(new java.awt.Color(0, 0, 0));
        jFmtTotal.setForeground(new java.awt.Color(255, 255, 255));
        jFmtTotal.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total");

        jCboPublicadoras.setBackground(new java.awt.Color(0, 0, 0));
        jCboPublicadoras.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jCboPublicadoras.setForeground(new java.awt.Color(255, 255, 255));
        jCboPublicadoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel4.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Publicadoras");

        jCboClientes.setBackground(new java.awt.Color(0, 0, 0));
        jCboClientes.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jCboClientes.setForeground(new java.awt.Color(255, 255, 255));
        jCboClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clientes");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data");

        jTxtCodigo.setBackground(new java.awt.Color(0, 0, 0));
        jTxtCodigo.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N
        jTxtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jTxtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel2.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Id");

        jBtnPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnPesquisar.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jBtnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/procurar.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnCancelar.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jBtnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnConfirmar.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jBtnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/verificar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jBtnExcluir.setBackground(new java.awt.Color(0, 0, 0));
        jBtnExcluir.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lixo.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setBackground(new java.awt.Color(0, 0, 0));
        jBtnAlterar.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jBtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lapis.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnIncluir.setBackground(new java.awt.Color(0, 0, 0));
        jBtnIncluir.setFont(new java.awt.Font("Papyrus", 1, 12)); // NOI18N
        jBtnIncluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/download.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jFmtData.setBackground(new java.awt.Color(0, 0, 0));
        jFmtData.setForeground(new java.awt.Color(255, 255, 255));
        jFmtData.setFont(new java.awt.Font("Papyrus", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jFmtData, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCboPublicadoras, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jFmtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBtnIncluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnAlterar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtnExcluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jBtnIncluir)
                            .addGap(5, 5, 5)
                            .addComponent(jBtnAlterar)
                            .addGap(5, 5, 5)
                            .addComponent(jBtnExcluir)
                            .addGap(5, 5, 5)
                            .addComponent(jBtnConfirmar)
                            .addGap(5, 5, 5)
                            .addComponent(jBtnCancelar)
                            .addGap(5, 5, 5)
                            .addComponent(jBtnPesquisar))))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCboClientes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFmtData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCboPublicadoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jBtnIncluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnIncluir)
                    .addComponent(jBtnAlterar)
                    .addComponent(jBtnExcluir)
                    .addComponent(jBtnConfirmar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnPesquisar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jFmtData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        incluir = false;
        
        Util.habilitar(true, jTxtCodigo, jFmtData, jCboClientes,  jCboPublicadoras, jFmtTotal,
            jBtnIncluir2,  jBtnAlterar2,  jBtnExcluir2,
            jBtnConfirmar,jBtnCancelar, jBtnExcluir);
        Util.habilitar(false,jBtnIncluir, jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboClientes, jCboPublicadoras, jFmtTotal);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        incluir = true;
        
        Util.habilitar(true, jFmtData, jCboClientes,  jCboPublicadoras, jFmtTotal,
            jBtnIncluir2,  jBtnAlterar2,  jBtnExcluir2,
            jBtnConfirmar,jBtnCancelar, jBtnExcluir);
        Util.habilitar(false,jBtnIncluir, jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboClientes, jCboPublicadoras, jFmtTotal);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        JDlgVendasPesquisar jDlgVendasPesquisar = new JDlgVendasPesquisar(null, true);
        jDlgVendasPesquisar.setTelaAnterior(this);
        jDlgVendasPesquisar.setVisible(true);
        Util.mensagem("omagah");
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false, jTxtCodigo, jFmtData, jCboClientes,  jCboPublicadoras, jFmtTotal,
            jBtnIncluir2,  jBtnAlterar2,  jBtnExcluir2,
            jBtnConfirmar,jBtnCancelar, jBtnExcluir);
        Util.habilitar(true,jBtnIncluir, jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboClientes, jCboPublicadoras, jFmtTotal);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
        VendasDAO vendasDAO = new VendasDAO();
        VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
        JceVendas jceVendas = viewBean();
        if (incluir == true) {
            vendasDAO.insert(jceVendas);
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                JceVendasProdutos jceVendasProdutos = controllerVendasProdutos.getBean(ind);
                JcePublicadoras jcePublicadoras = null;
                jceVendasProdutos.setJcePublicadoras(jcePublicadoras);
                vendasProdutosDAO.insert(jceVendasProdutos);
            }
        } else {
            vendasDAO.update(jceVendas);
        }

        Util.habilitar(false, jTxtCodigo, jFmtData, jCboClientes,  jCboPublicadoras, jFmtTotal,
            jBtnIncluir2,  jBtnAlterar2,  jBtnExcluir2,
            jBtnConfirmar,jBtnCancelar, jBtnExcluir);
        Util.habilitar(true,jBtnIncluir, jBtnAlterar);
        Util.limpar(jTxtCodigo, jFmtData, jCboClientes, jCboPublicadoras, jFmtTotal);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Util.perguntar("Deseja excluir ?") == true) {
            VendasDAO vendasDAO = new VendasDAO();
            VendasProdutosDAO vendasProdutosDAO = new VendasProdutosDAO();
            for (int ind = 0; ind < jTable1.getRowCount(); ind++) {
                JceVendasProdutos jceVendasProdutos = controllerVendasProdutos.getBean(ind);
                vendasProdutosDAO.delete(jceVendasProdutos);
            }
            vendasDAO.delete(viewBean());
        }

        Util.habilitar(false, jTxtCodigo, jFmtData, jCboClientes,  jCboPublicadoras, jFmtTotal,
            jBtnIncluir2,  jBtnAlterar2,  jBtnExcluir2,
            jBtnConfirmar,jBtnCancelar, jBtnExcluir);
        Util.habilitar(true,jBtnIncluir, jBtnAlterar);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendas dialog = new JDlgVendas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnAlterar2;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnExcluir2;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnIncluir2;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<JceClientes> jCboClientes;
    private javax.swing.JComboBox<JcePublicadoras> jCboPublicadoras;
    private javax.swing.JFormattedTextField jFmtData;
    private javax.swing.JFormattedTextField jFmtTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCodigo;
    // End of variables declaration//GEN-END:variables
}
