package bean;
// Generated 16/12/2025 12:58:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JceClientes generated by hbm2java
 */
@Entity
@Table(name="jce_clientes"
    ,catalog="db_joao_escobar"
)
public class JceClientes  implements java.io.Serializable {


     private int jceIdclientes;
     private String jceNome;
     private String jceApelido;
     private String jceEmail;
     private String jceSenha;
     private Date jceData;
     private String jceTelefone;
     private String jceLocalizacao;
     private String jceBio;
     private int jceStatus;
     private int jceGenero;
     private String jceCep;

    public JceClientes() {
    }

	
    public JceClientes(int jceIdclientes, String jceNome, String jceApelido, String jceEmail, String jceSenha, String jceTelefone) {
        this.jceIdclientes = jceIdclientes;
        this.jceNome = jceNome;
        this.jceApelido = jceApelido;
        this.jceEmail = jceEmail;
        this.jceSenha = jceSenha;
        this.jceTelefone = jceTelefone;
    }
    public JceClientes(int jceIdclientes, String jceNome, String jceApelido, String jceEmail, String jceSenha, Date jceData, String jceTelefone, String jceLocalizacao, String jceBio) {
       this.jceIdclientes = jceIdclientes;
       this.jceNome = jceNome;
       this.jceApelido = jceApelido;
       this.jceEmail = jceEmail;
       this.jceSenha = jceSenha;
       this.jceData = jceData;
       this.jceTelefone = jceTelefone;
       this.jceLocalizacao = jceLocalizacao;
       this.jceBio = jceBio;
       this.jceStatus = jceStatus;
       this.jceGenero = jceGenero;
       this.jceCep = jceCep;
    }
   
     @Id 

    
    @Column(name="jce_idclientes", unique=true, nullable=false)
    public int getJceIdclientes() {
        return this.jceIdclientes;
    }
    
    public void setJceIdclientes(int jceIdclientes) {
        this.jceIdclientes = jceIdclientes;
    }

    
    @Column(name="jce_nome", nullable=false, length=50)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    
    @Column(name="jce_apelido", nullable=false, length=50)
    public String getJceApelido() {
        return this.jceApelido;
    }
    
    public void setJceApelido(String jceApelido) {
        this.jceApelido = jceApelido;
    }

    
    @Column(name="jce_email", nullable=false, length=50)
    public String getJceEmail() {
        return this.jceEmail;
    }
    
    public void setJceEmail(String jceEmail) {
        this.jceEmail = jceEmail;
    }

    
    @Column(name="jce_senha", nullable=false, length=30)
    public String getJceSenha() {
        return this.jceSenha;
    }
    
    public void setJceSenha(String jceSenha) {
        this.jceSenha = jceSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_data", length=10)
    public Date getJceData() {
        return this.jceData;
    }
    
    public void setJceData(Date jceData) {
        this.jceData = jceData;
    }

    
    @Column(name="jce_telefone", nullable=false, length=14)
    public String getJceTelefone() {
        return this.jceTelefone;
    }
    
    public void setJceTelefone(String jceTelefone) {
        this.jceTelefone = jceTelefone;
    }

    
    @Column(name="jce_localizacao", length=40)
    public String getJceLocalizacao() {
        return this.jceLocalizacao;
    }
    
    public void setJceLocalizacao(String jceLocalizacao) {
        this.jceLocalizacao = jceLocalizacao;
    }

    
    @Column(name="jce_bio", length=50)
    public String getJceBio() {
        return this.jceBio;
    }
    
    public void setJceBio(String jceBio) {
        this.jceBio = jceBio;
    }

    
    @Column(name="jce_status")
    public int getJceStatus() {
        return this.jceStatus;
    }
    
    public void setJceStatus(int jceStatus) {
        this.jceStatus = jceStatus;
    }

    
    @Column(name="jce_genero")
    public int getJceGenero() {
        return this.jceGenero;
    }
    
    public void setJceGenero(int jceGenero) {
        this.jceGenero = jceGenero;
    }

    
    @Column(name="jce_cep", length=9)
    public String getJceCep() {
        return this.jceCep;
    }
    
    public void setJceCep(String jceCep) {
        this.jceCep = jceCep;
    }
    
    @Override
    public String toString() {
        return this.jceNome;
    }
    
    public boolean equals(Object object) {
        if (object instanceof JceClientes) {
            JceClientes jceClientes = (JceClientes) object;
            if (this.getJceIdclientes()== jceClientes.getJceIdclientes()) {
                return true;
            }
        }
        return false;
    }
}