package bean;
// Generated 03/11/2025 08:01:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JceClientes generated by hbm2java
 */
@Entity
@Table(name="jce_clientes"
    ,catalog="db_joao_escobar"
)
public class JceClientes  implements java.io.Serializable {


     private int idjceClientes;
     private String jceNome;
     private String jceApelido;
     private String jceEmail;
     private String jceSenha;
     private Date jceData;
     private String jceTelefone;
     private String jceLocalizacao;
     private String jceBio;
     private Integer jceStatus;
     private Integer jceGenero;
     private String jceGasto;
     private Set jceVendases = new HashSet(0);

    public JceClientes() {
    }

	
    public JceClientes(int idjceClientes, String jceNome, String jceApelido, String jceEmail, String jceSenha, String jceTelefone) {
        this.idjceClientes = idjceClientes;
        this.jceNome = jceNome;
        this.jceApelido = jceApelido;
        this.jceEmail = jceEmail;
        this.jceSenha = jceSenha;
        this.jceTelefone = jceTelefone;
    }
    public JceClientes(int idjceClientes, String jceNome, String jceApelido, String jceEmail, String jceSenha, Date jceData, String jceTelefone, String jceLocalizacao, String jceBio, Integer jceStatus, Integer jceGenero, String jceGasto, Set jceVendases) {
       this.idjceClientes = idjceClientes;
       this.jceNome = jceNome;
       this.jceApelido = jceApelido;
       this.jceEmail = jceEmail;
       this.jceSenha = jceSenha;
       this.jceData = jceData;
       this.jceTelefone = jceTelefone;
       this.jceLocalizacao = jceLocalizacao;
       this.jceBio = jceBio;
       this.jceStatus = jceStatus;
       this.jceGenero = jceGenero;
       this.jceGasto = jceGasto;
       this.jceVendases = jceVendases;
    }
   
     @Id 

    
    @Column(name="idjce_clientes", unique=true, nullable=false)
    public int getIdjceClientes() {
        return this.idjceClientes;
    }
    
    public void setIdjceClientes(int idjceClientes) {
        this.idjceClientes = idjceClientes;
    }

    
    @Column(name="jce_nome", nullable=false, length=50)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    
    @Column(name="jce_apelido", nullable=false, length=50)
    public String getJceApelido() {
        return this.jceApelido;
    }
    
    public void setJceApelido(String jceApelido) {
        this.jceApelido = jceApelido;
    }

    
    @Column(name="jce_email", nullable=false, length=50)
    public String getJceEmail() {
        return this.jceEmail;
    }
    
    public void setJceEmail(String jceEmail) {
        this.jceEmail = jceEmail;
    }

    
    @Column(name="jce_senha", nullable=false, length=30)
    public String getJceSenha() {
        return this.jceSenha;
    }
    
    public void setJceSenha(String jceSenha) {
        this.jceSenha = jceSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_data", length=10)
    public Date getJceData() {
        return this.jceData;
    }
    
    public void setJceData(Date jceData) {
        this.jceData = jceData;
    }

    
    @Column(name="jce_telefone", nullable=false, length=10)
    public String getJceTelefone() {
        return this.jceTelefone;
    }
    
    public void setJceTelefone(String jceTelefone) {
        this.jceTelefone = jceTelefone;
    }

    
    @Column(name="jce_localizacao", length=40)
    public String getJceLocalizacao() {
        return this.jceLocalizacao;
    }
    
    public void setJceLocalizacao(String jceLocalizacao) {
        this.jceLocalizacao = jceLocalizacao;
    }

    
    @Column(name="jce_bio", length=50)
    public String getJceBio() {
        return this.jceBio;
    }
    
    public void setJceBio(String jceBio) {
        this.jceBio = jceBio;
    }

    
    @Column(name="jce_status")
    public Integer getJceStatus() {
        return this.jceStatus;
    }
    
    public void setJceStatus(Integer jceStatus) {
        this.jceStatus = jceStatus;
    }

    
    @Column(name="jce_genero")
    public Integer getJceGenero() {
        return this.jceGenero;
    }
    
    public void setJceGenero(Integer jceGenero) {
        this.jceGenero = jceGenero;
    }

    
    @Column(name="jce_gasto", length=10)
    public String getJceGasto() {
        return this.jceGasto;
    }
    
    public void setJceGasto(String jceGasto) {
        this.jceGasto = jceGasto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jceClientes")
    public Set getJceVendases() {
        return this.jceVendases;
    }
    
    public void setJceVendases(Set jceVendases) {
        this.jceVendases = jceVendases;
    }




}


