package bean;
// Generated 06/10/2025 10:55:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JceClientes generated by hbm2java
 */
@Entity
@Table(name="jce_clientes"
    ,catalog="db_joao_escobar"
)
public class JceClientes  implements java.io.Serializable {


     private int idjceClientes;
     private String jceNome;
     private String jceApelido;
     private String jceEmail;
     private String jceSenha;
     private Date jceDatanasc;
     private String jceTelefone;
     private String jceLocalizacao;
     private int jceAvatar;
     private String jceStatus;
     private String jceGenero;
     private String jceBio;
     private int jceGasto;
     private JceVendas jceVendas;

    public JceClientes() {
    }

	
    public JceClientes(int idjceClientes, String jceNome, String jceEmail, String jceSenha, String jceTelefone) {
        this.idjceClientes = idjceClientes;
        this.jceNome = jceNome;
        this.jceEmail = jceEmail;
        this.jceSenha = jceSenha;
        this.jceTelefone = jceTelefone;
    }
    public JceClientes(int idjceClientes, String jceNome, String jceApelido, String jceEmail, String jceSenha, Date jceDatanasc, String jceTelefone, String jceLocalizacao, int jceAvatar, String jceStatus, String jceGenero, String jceBio, int jceGasto, JceVendas jceVendas) {
       this.idjceClientes = idjceClientes;
       this.jceNome = jceNome;
       this.jceApelido = jceApelido;
       this.jceEmail = jceEmail;
       this.jceSenha = jceSenha;
       this.jceDatanasc = jceDatanasc;
       this.jceTelefone = jceTelefone;
       this.jceLocalizacao = jceLocalizacao;
       this.jceAvatar = jceAvatar;
       this.jceStatus = jceStatus;
       this.jceGenero = jceGenero;
       this.jceBio = jceBio;
       this.jceGasto = jceGasto;
       this.jceVendas = jceVendas;
    }
   
     @Id 

    
    @Column(name="idjce_clientes", unique=true, nullable=false)
    public int getIdjceClientes() {
        return this.idjceClientes;
    }
    
    public void setIdjceClientes(int idjceClientes) {
        this.idjceClientes = idjceClientes;
    }

    
    @Column(name="jce_nome", nullable=false, length=50)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    
    @Column(name="jce_apelido", length=50)
    public String getJceApelido() {
        return this.jceApelido;
    }
    
    public void setJceApelido(String jceApelido) {
        this.jceApelido = jceApelido;
    }

    
    @Column(name="jce_email", nullable=false, length=50)
    public String getJceEmail() {
        return this.jceEmail;
    }
    
    public void setJceEmail(String jceEmail) {
        this.jceEmail = jceEmail;
    }

    
    @Column(name="jce_senha", nullable=false, length=30)
    public String getJceSenha() {
        return this.jceSenha;
    }
    
    public void setJceSenha(String jceSenha) {
        this.jceSenha = jceSenha;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_datanasc", length=10)
    public Date getJceDatanasc() {
        return this.jceDatanasc;
    }
    
    public void setJceDatanasc(Date jceDatanasc) {
        this.jceDatanasc = jceDatanasc;
    }

    
    @Column(name="jce_telefone", nullable=false, length=10)
    public String getJceTelefone() {
        return this.jceTelefone;
    }
    
    public void setJceTelefone(String jceTelefone) {
        this.jceTelefone = jceTelefone;
    }

    
    @Column(name="jce_localizacao", length=40)
    public String getJceLocalizacao() {
        return this.jceLocalizacao;
    }
    
    public void setJceLocalizacao(String jceLocalizacao) {
        this.jceLocalizacao = jceLocalizacao;
    }

    
    @Column(name="jce_avatar")
    public int getJceAvatar() {
        return this.jceAvatar;
    }
    
    public void setJceAvatar(int jceAvatar) {
        this.jceAvatar = jceAvatar;
    }

    
    @Column(name="jce_status", length=45)
    public String getJceStatus() {
        return this.jceStatus;
    }
    
    public void setJceStatus(String jceStatus) {
        this.jceStatus = jceStatus;
    }

    
    @Column(name="jce_genero", length=2)
    public String getJceGenero() {
        return this.jceGenero;
    }
    
    public void setJceGenero(String jceGenero) {
        this.jceGenero = jceGenero;
    }

    
    @Column(name="jce_rank", length=5)
    public String getJceRank() {
        return this.jceBio;
    }
    
    public void setJceRank(String jceBio) {
        this.jceBio = jceBio;
    }

    
    @Column(name="jce_dinheiroGasto", precision=22, scale=0)
    public int getJceDinheiroGasto() {
        return this.jceGasto;
    }
    
    public void setJceDinheiroGasto(int jceGasto) {
        this.jceGasto = jceGasto;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="jceClientes")
    public JceVendas getJceVendas() {
        return this.jceVendas;
    }
    
    public void setJceVendas(JceVendas jceVendas) {
        this.jceVendas = jceVendas;
    }




}


