package bean;
// Generated 26/11/2025 10:15:25 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JceHqs generated by hbm2java
 */
@Entity
@Table(name="jce_hqs"
    ,catalog="db_joao_escobar"
)
public class JceHqs  implements java.io.Serializable {


     private int jceIdhqs;
     private String jceNome;
     private int jceCapitulos;
     private String jceGenero;
     private Date jceLancamento;
     private String jceCriador;
     private String jcePublicadora;
     private String jceTags;

    public JceHqs() {
    }

	
    public JceHqs(int jceIdhqs, String jceNome, int jceCapitulos, String jceCriador, String jcePublicadora) {
        this.jceIdhqs = jceIdhqs;
        this.jceNome = jceNome;
        this.jceCapitulos = jceCapitulos;
        this.jceCriador = jceCriador;
        this.jcePublicadora = jcePublicadora;
    }
    public JceHqs(int jceIdhqs, String jceNome, int jceCapitulos, String jceGenero, Date jceLancamento, String jceCriador, String jcePublicadora, String jceTags, Set jceVendasProdutoses) {
       this.jceIdhqs = jceIdhqs;
       this.jceNome = jceNome;
       this.jceCapitulos = jceCapitulos;
       this.jceGenero = jceGenero;
       this.jceLancamento = jceLancamento;
       this.jceCriador = jceCriador;
       this.jcePublicadora = jcePublicadora;
       this.jceTags = jceTags;
    }
   
     @Id 

    
    @Column(name="jce_idhqs", unique=true, nullable=false)
    public int getJceIdhqs() {
        return this.jceIdhqs;
    }
    
    public void setJceIdhqs(int jceIdhqs) {
        this.jceIdhqs = jceIdhqs;
    }

    
    @Column(name="jce_nome", nullable=false, length=50)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    
    @Column(name="jce_capitulos", nullable=false, precision=22, scale=0)
    public int getJceCapitulos() {
        return this.jceCapitulos;
    }
    
    public void setJceCapitulos(int jceCapitulos) {
        this.jceCapitulos = jceCapitulos;
    }

    
    @Column(name="jce_genero", length=50)
    public String getJceGenero() {
        return this.jceGenero;
    }
    
    public void setJceGenero(String jceGenero) {
        this.jceGenero = jceGenero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_lancamento", length=10)
    public Date getJceLancamento() {
        return this.jceLancamento;
    }
    
    public void setJceLancamento(Date jceLancamento) {
        this.jceLancamento = jceLancamento;
    }

    
    @Column(name="jce_criador", nullable=false, length=50)
    public String getJceCriador() {
        return this.jceCriador;
    }
    
    public void setJceCriador(String jceCriador) {
        this.jceCriador = jceCriador;
    }

    
    @Column(name="jce_publicadora", nullable=false, length=50)
    public String getJcePublicadora() {
        return this.jcePublicadora;
    }
    
    public void setJcePublicadora(String jcePublicadora) {
        this.jcePublicadora = jcePublicadora;
    }

    
    @Column(name="jce_tags", length=100)
    public String getJceTags() {
        return this.jceTags;
    }
    
    public void setJceTags(String jceTags) {
        this.jceTags = jceTags;
    }
}


