package bean;
// Generated 03/11/2025 08:01:43 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * JcePublicadoras generated by hbm2java
 */
@Entity
@Table(name="jce_publicadoras"
    ,catalog="db_joao_escobar"
    , uniqueConstraints = @UniqueConstraint(columnNames="jce_nome") 
)
public class JcePublicadoras  implements java.io.Serializable {


     private int jceIdpublicadoras;
     private String jceNome;
     private Date jceCriada;
     private Integer jceStatus;
     private String jceEmail;
     private String jceSenha;
     private String jceTelefone;
     private String jceSeed;
     private String jceDescricao;
     private Set jceVendases = new HashSet(0);

    public JcePublicadoras() {
    }

	
    public JcePublicadoras(int jceIdpublicadoras, String jceNome, String jceEmail, String jceSenha, String jceTelefone) {
        this.jceIdpublicadoras = jceIdpublicadoras;
        this.jceNome = jceNome;
        this.jceEmail = jceEmail;
        this.jceSenha = jceSenha;
        this.jceTelefone = jceTelefone;
    }
    public JcePublicadoras(int jceIdpublicadoras, String jceNome, Date jceCriada, Integer jceStatus, String jceEmail, String jceSenha, String jceTelefone, String jceSeed, String jceDescricao, Set jceVendases) {
       this.jceIdpublicadoras = jceIdpublicadoras;
       this.jceNome = jceNome;
       this.jceCriada = jceCriada;
       this.jceStatus = jceStatus;
       this.jceEmail = jceEmail;
       this.jceSenha = jceSenha;
       this.jceTelefone = jceTelefone;
       this.jceSeed = jceSeed;
       this.jceDescricao = jceDescricao;
       this.jceVendases = jceVendases;
    }
   
     @Id 

    
    @Column(name="jce_idpublicadoras", unique=true, nullable=false)
    public int getJceIdpublicadoras() {
        return this.jceIdpublicadoras;
    }
    
    public void setJceIdpublicadoras(int jceIdpublicadoras) {
        this.jceIdpublicadoras = jceIdpublicadoras;
    }

    
    @Column(name="jce_nome", unique=true, nullable=false, length=50)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_criada", length=10)
    public Date getJceCriada() {
        return this.jceCriada;
    }
    
    public void setJceCriada(Date jceCriada) {
        this.jceCriada = jceCriada;
    }

    
    @Column(name="jce_status")
    public Integer getJceStatus() {
        return this.jceStatus;
    }
    
    public void setJceStatus(Integer jceStatus) {
        this.jceStatus = jceStatus;
    }

    
    @Column(name="jce_email", nullable=false, length=50)
    public String getJceEmail() {
        return this.jceEmail;
    }
    
    public void setJceEmail(String jceEmail) {
        this.jceEmail = jceEmail;
    }

    
    @Column(name="jce_senha", nullable=false, length=30)
    public String getJceSenha() {
        return this.jceSenha;
    }
    
    public void setJceSenha(String jceSenha) {
        this.jceSenha = jceSenha;
    }

    
    @Column(name="jce_telefone", nullable=false, length=10)
    public String getJceTelefone() {
        return this.jceTelefone;
    }
    
    public void setJceTelefone(String jceTelefone) {
        this.jceTelefone = jceTelefone;
    }

    
    @Column(name="jce_seed", length=45)
    public String getJceSeed() {
        return this.jceSeed;
    }
    
    public void setJceSeed(String jceSeed) {
        this.jceSeed = jceSeed;
    }

    
    @Column(name="jce_descricao", length=100)
    public String getJceDescricao() {
        return this.jceDescricao;
    }
    
    public void setJceDescricao(String jceDescricao) {
        this.jceDescricao = jceDescricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jcePublicadoras")
    public Set getJceVendases() {
        return this.jceVendases;
    }
    
    public void setJceVendases(Set jceVendases) {
        this.jceVendases = jceVendases;
    }




}


