package bean;
// Generated 06/10/2025 10:55:53 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JcePublicadoras generated by hbm2java
 */
@Entity
@Table(name="jce_publicadoras"
    ,catalog="db_joao_escobar"
)
public class JcePublicadoras  implements java.io.Serializable {


     private int jceIdpublicadoras;
     private String jceNome;
     private Date jceCriadaEm;
     private String jceEmail;
     private String jceSenha;
     private String jceTelefone;
     private String jceSeed;
     private Integer jceStatus;
     private String jceDescricao;
     private JceVendas jceVendas;

    public JcePublicadoras() {
    }

	
    public JcePublicadoras(int jceIdpublicadoras, String jceNome, String jceEmail, String jceSenha, String jceTelefone) {
        this.jceIdpublicadoras = jceIdpublicadoras;
        this.jceNome = jceNome;
        this.jceEmail = jceEmail;
        this.jceSenha = jceSenha;
        this.jceTelefone = jceTelefone;
    }
    public JcePublicadoras(int jceIdpublicadoras, String jceNome, Date jceCriadaEm, String jceEmail, String jceSenha, String jceTelefone, String jceSeed, Integer jceStatus, String jceDescricao, JceVendas jceVendas) {
       this.jceIdpublicadoras = jceIdpublicadoras;
       this.jceNome = jceNome;
       this.jceCriadaEm = jceCriadaEm;
       this.jceEmail = jceEmail;
       this.jceSenha = jceSenha;
       this.jceTelefone = jceTelefone;
       this.jceSeed = jceSeed;
       this.jceStatus = jceStatus;
       this.jceDescricao = jceDescricao;
       this.jceVendas = jceVendas;
    }
   
     @Id 

    
    @Column(name="jce_idpublicadoras", unique=true, nullable=false)
    public int getJceIdpublicadoras() {
        return this.jceIdpublicadoras;
    }
    
    public void setJceIdpublicadoras(int jceIdpublicadoras) {
        this.jceIdpublicadoras = jceIdpublicadoras;
    }

    
    @Column(name="jce_nome", nullable=false, length=45)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_criadaEm", length=10)
    public Date getJceCriadaEm() {
        return this.jceCriadaEm;
    }
    
    public void setJceCriadaEm(Date jceCriadaEm) {
        this.jceCriadaEm = jceCriadaEm;
    }

    
    @Column(name="jce_email", nullable=false, length=50)
    public String getJceEmail() {
        return this.jceEmail;
    }
    
    public void setJceEmail(String jceEmail) {
        this.jceEmail = jceEmail;
    }

    
    @Column(name="jce_senha", nullable=false, length=30)
    public String getJceSenha() {
        return this.jceSenha;
    }
    
    public void setJceSenha(String jceSenha) {
        this.jceSenha = jceSenha;
    }

    
    @Column(name="jce_telefone", nullable=false, length=10)
    public String getJceTelefone() {
        return this.jceTelefone;
    }
    
    public void setJceTelefone(String jceTelefone) {
        this.jceTelefone = jceTelefone;
    }

    
    @Column(name="jce_seed", length=45)
    public String getJceSeed() {
        return this.jceSeed;
    }
    
    public void setJceSeed(String jceSeed) {
        this.jceSeed = jceSeed;
    }

    
    @Column(name="jce_status")
    public Integer getJceStatus() {
        return this.jceStatus;
    }
    
    public void setJceStatus(Integer jceStatus) {
        this.jceStatus = jceStatus;
    }

    
    @Column(name="jce_descricao", length=100)
    public String getJceDescricao() {
        return this.jceDescricao;
    }
    
    public void setJceDescricao(String jceDescricao) {
        this.jceDescricao = jceDescricao;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="jceClientes")
    public JceVendas getJceVendas() {
        return this.jceVendas;
    }
    
    public void setJceVendas(JceVendas jceVendas) {
        this.jceVendas = jceVendas;
    }




}


