package bean;
// Generated 12/12/2025 17:07:27 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * JceUsuarios generated by hbm2java
 */
@Entity
@Table(name="jce_usuarios"
    ,catalog="db_joao_escobar"
    , uniqueConstraints = @UniqueConstraint(columnNames="jce_apelido") 
)
public class JceUsuarios  implements java.io.Serializable {


     private int jceIdusuarios;
     private String jceNome;
     private String jceApelido;
     private String jceCpf;
     private Date jceDataNascimento;
     private String jceSenha;
     private Integer jceNivel;
     private String jceAtivo;

    public JceUsuarios() {
    }

	
    public JceUsuarios(int jceIdusuarios, String jceNome, String jceApelido, String jceCpf, String jceSenha) {
        this.jceIdusuarios = jceIdusuarios;
        this.jceNome = jceNome;
        this.jceApelido = jceApelido;
        this.jceCpf = jceCpf;
        this.jceSenha = jceSenha;
    }
    public JceUsuarios(int jceIdusuarios, String jceNome, String jceApelido, String jceCpf, Date jceDataNascimento, String jceSenha, Integer jceNivel, String jceAtivo) {
       this.jceIdusuarios = jceIdusuarios;
       this.jceNome = jceNome;
       this.jceApelido = jceApelido;
       this.jceCpf = jceCpf;
       this.jceDataNascimento = jceDataNascimento;
       this.jceSenha = jceSenha;
       this.jceNivel = jceNivel;
       this.jceAtivo = jceAtivo;
    }
   
     @Id 

    
    @Column(name="jce_idusuarios", unique=true, nullable=false)
    public int getJceIdusuarios() {
        return this.jceIdusuarios;
    }
    
    public void setJceIdusuarios(int jceIdusuarios) {
        this.jceIdusuarios = jceIdusuarios;
    }

    
    @Column(name="jce_nome", nullable=false, length=50)
    public String getJceNome() {
        return this.jceNome;
    }
    
    public void setJceNome(String jceNome) {
        this.jceNome = jceNome;
    }

    
    @Column(name="jce_apelido", unique=true, nullable=false, length=50)
    public String getJceApelido() {
        return this.jceApelido;
    }
    
    public void setJceApelido(String jceApelido) {
        this.jceApelido = jceApelido;
    }

    
    @Column(name="jce_cpf", nullable=false, length=14)
    public String getJceCpf() {
        return this.jceCpf;
    }
    
    public void setJceCpf(String jceCpf) {
        this.jceCpf = jceCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_dataNascimento", length=10)
    public Date getJceDataNascimento() {
        return this.jceDataNascimento;
    }
    
    public void setJceDataNascimento(Date jceDataNascimento) {
        this.jceDataNascimento = jceDataNascimento;
    }

    
    @Column(name="jce_senha", nullable=false, length=30)
    public String getJceSenha() {
        return this.jceSenha;
    }
    
    public void setJceSenha(String jceSenha) {
        this.jceSenha = jceSenha;
    }

    
    @Column(name="jce_nivel")
    public Integer getJceNivel() {
        return this.jceNivel;
    }
    
    public void setJceNivel(Integer jceNivel) {
        this.jceNivel = jceNivel;
    }

    
    @Column(name="jce_ativo", length=1)
    public String getJceAtivo() {
        return this.jceAtivo;
    }
    
    public void setJceAtivo(String jceAtivo) {
        this.jceAtivo = jceAtivo;
    }




}


