package bean;
// Generated 12/12/2025 17:07:27 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JceVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="jce_vendasProdutos"
    ,catalog="db_joao_escobar"
)
public class JceVendasProdutos  implements java.io.Serializable {


     private int idjceVendasProdutos;
     private JceHqs jceHqs;
     private JcePublicadoras jcePublicadoras;
     private Integer jceQuantidade;
     private double jceValorUnitario;

    public JceVendasProdutos() {
    }

	
    public JceVendasProdutos(int idjceVendasProdutos) {
        this.idjceVendasProdutos = idjceVendasProdutos;
    }
    public JceVendasProdutos(int idjceVendasProdutos, JceHqs jceHqs, JcePublicadoras jcePublicadoras, Integer jceQuantidade, double jceValorUnitario) {
       this.idjceVendasProdutos = idjceVendasProdutos;
       this.jceHqs = jceHqs;
       this.jcePublicadoras = jcePublicadoras;
       this.jceQuantidade = jceQuantidade;
       this.jceValorUnitario = jceValorUnitario;
    }
   
     @Id 

    
    @Column(name="idjce_vendasProdutos", unique=true, nullable=false)
    public int getIdjceVendasProdutos() {
        return this.idjceVendasProdutos;
    }
    
    public void setIdjceVendasProdutos(int idjceVendasProdutos) {
        this.idjceVendasProdutos = idjceVendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_produtos")
    public JceHqs getJceHqs() {
        return this.jceHqs;
    }
    
    public void setJceHqs(JceHqs jceHqs) {
        this.jceHqs = jceHqs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_publicadoras")
    public JcePublicadoras getJcePublicadoras() {
        return this.jcePublicadoras;
    }
    
    public void setJcePublicadoras(JcePublicadoras jcePublicadoras) {
        this.jcePublicadoras = jcePublicadoras;
    }

    
    @Column(name="jce_quantidade")
    public Integer getJceQuantidade() {
        return this.jceQuantidade;
    }
    
    public void setJceQuantidade(Integer jceQuantidade) {
        this.jceQuantidade = jceQuantidade;
    }

    
    @Column(name="jce_valorUnitario", precision=7)
    public double getJceValorUnitario() {
        return this.jceValorUnitario;
    }
    
    public void setJceValorUnitario(double jceValorUnitario) {
        this.jceValorUnitario = jceValorUnitario;
    }




}


