package bean;
// Generated 16/12/2025 12:58:38 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JceVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="jce_vendasProdutos"
    ,catalog="db_joao_escobar"
)
public class JceVendasProdutos  implements java.io.Serializable {


     private int jceIdvendasProdutos;
     private JceHqs jceHqs;
     private JcePublicadoras jcePublicadoras;
     private int jceQuantidade;
     private double jceValorUnitario;

    public JceVendasProdutos() {
    }

	
    public JceVendasProdutos(int jceIdvendasProdutos) {
        this.jceIdvendasProdutos = jceIdvendasProdutos;
    }
    public JceVendasProdutos(int jceIdvendasProdutos, JceHqs jceHqs, JcePublicadoras jcePublicadoras, int jceQuantidade, double jceValorUnitario) {
       this.jceIdvendasProdutos = jceIdvendasProdutos;
       this.jceHqs = jceHqs;
       this.jcePublicadoras = jcePublicadoras;
       this.jceQuantidade = jceQuantidade;
       this.jceValorUnitario = jceValorUnitario;
    }
   
     @Id 

    
    @Column(name="jce_idvendasProdutos", unique=true, nullable=false)
    public int getJceIdvendasProdutos() {
        return this.jceIdvendasProdutos;
    }
    
    public void setJceIdvendasProdutos(int jceIdvendasProdutos) {
        this.jceIdvendasProdutos = jceIdvendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_produtos")
    public JceHqs getJceHqs() {
        return this.jceHqs;
    }
    
    public void setJceHqs(JceHqs jceHqs) {
        this.jceHqs = jceHqs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_publicadoras")
    public JcePublicadoras getJcePublicadoras() {
        return this.jcePublicadoras;
    }
    
    public void setJcePublicadoras(JcePublicadoras jcePublicadoras) {
        this.jcePublicadoras = jcePublicadoras;
    }

    
    @Column(name="jce_quantidade")
    public int getJceQuantidade() {
        return this.jceQuantidade;
    }
    
    public void setJceQuantidade(int jceQuantidade) {
        this.jceQuantidade = jceQuantidade;
    }

    
    @Column(name="jce_valorUnitario", precision=7)
    public double getJceValorUnitario() {
        return this.jceValorUnitario;
    }
    
    public void setJceValorUnitario(double jceValorUnitario) {
        this.jceValorUnitario = jceValorUnitario;
    }




}


