package bean;
// Generated 16/12/2025 12:58:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JceVendas generated by hbm2java
 */
@Entity
@Table(name="jce_vendas"
    ,catalog="db_joao_escobar"
)
public class JceVendas  implements java.io.Serializable {


     private int jceIdvendas;
     private JceClientes jceClientes;
     private JcePublicadoras jcePublicadoras;
     private Date jceData;
     private double jceTotal;

    public JceVendas() {
    }

    public JceVendas(int jceIdvendas, JceClientes jceClientes, JcePublicadoras jcePublicadoras, Date jceData, double jceTotal) {
       this.jceIdvendas = jceIdvendas;
       this.jceClientes = jceClientes;
       this.jcePublicadoras = jcePublicadoras;
       this.jceData = jceData;
       this.jceTotal = jceTotal;
    }
   
     @Id 

    
    @Column(name="jce_idvendas", unique=true, nullable=false)
    public int getJceIdvendas() {
        return this.jceIdvendas;
    }
    
    public void setJceIdvendas(int jceIdvendas) {
        this.jceIdvendas = jceIdvendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_clientes", nullable=false)
    public JceClientes getJceClientes() {
        return this.jceClientes;
    }
    
    public void setJceClientes(JceClientes jceClientes) {
        this.jceClientes = jceClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_publicadoras", nullable=false)
    public JcePublicadoras getJcePublicadoras() {
        return this.jcePublicadoras;
    }
    
    public void setJcePublicadoras(JcePublicadoras jcePublicadoras) {
        this.jcePublicadoras = jcePublicadoras;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jce_data", nullable=false, length=10)
    public Date getJceData() {
        return this.jceData;
    }
    
    public void setJceData(Date jceData) {
        this.jceData = jceData;
    }

    
    @Column(name="jce_total", nullable=false, precision=22, scale=0)
    public double getJceTotal() {
        return this.jceTotal;
    }
    
    public void setJceTotal(double jceTotal) {
        this.jceTotal = jceTotal;
    }




}


