package bean;
// Generated 06/10/2025 10:55:53 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * JceVendas generated by hbm2java
 */
@Entity
@Table(name="jce_vendas"
    ,catalog="db_joao_escobar"
)
public class JceVendas  implements java.io.Serializable {


     private int idvendas;
     private JceClientes jceClientes;
     private JcePublicadoras jcePublicadoras;
     private String numpedido;
     private Integer clientes;
     private Integer publicadoras;
     private double total;

    public JceVendas() {
    }

	
    public JceVendas(JceClientes jceClientes, JcePublicadoras jcePublicadoras, String numpedido, double total) {
        this.jceClientes = jceClientes;
        this.jcePublicadoras = jcePublicadoras;
        this.numpedido = numpedido;
        this.total = total;
    }
    public JceVendas(JceClientes jceClientes, JcePublicadoras jcePublicadoras, String numpedido, Integer clientes, Integer publicadoras, double total) {
       this.jceClientes = jceClientes;
       this.jcePublicadoras = jcePublicadoras;
       this.numpedido = numpedido;
       this.clientes = clientes;
       this.publicadoras = publicadoras;
       this.total = total;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="jceClientes"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idvendas", unique=true, nullable=false)
    public int getIdvendas() {
        return this.idvendas;
    }
    
    public void setIdvendas(int idvendas) {
        this.idvendas = idvendas;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public JceClientes getJceClientes() {
        return this.jceClientes;
    }
    
    public void setJceClientes(JceClientes jceClientes) {
        this.jceClientes = jceClientes;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public JcePublicadoras getJcePublicadoras() {
        return this.jcePublicadoras;
    }
    
    public void setJcePublicadoras(JcePublicadoras jcePublicadoras) {
        this.jcePublicadoras = jcePublicadoras;
    }

    
    @Column(name="numpedido", nullable=false, length=10)
    public String getNumpedido() {
        return this.numpedido;
    }
    
    public void setNumpedido(String numpedido) {
        this.numpedido = numpedido;
    }

    
    @Column(name="clientes")
    public Integer getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Integer clientes) {
        this.clientes = clientes;
    }

    
    @Column(name="publicadoras")
    public Integer getPublicadoras() {
        return this.publicadoras;
    }
    
    public void setPublicadoras(Integer publicadoras) {
        this.publicadoras = publicadoras;
    }

    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


