package bean;
// Generated 03/11/2025 08:01:43 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JceVendas generated by hbm2java
 */
@Entity
@Table(name="jce_vendas"
    ,catalog="db_joao_escobar"
)
public class JceVendas  implements java.io.Serializable {


     private int jceIdvendas;
     private JceClientes jceClientes;
     private JcePublicadoras jcePublicadoras;
     private String jceNumpedido;
     private double jceTotal;

    public JceVendas() {
    }

    public JceVendas(int jceIdvendas, JceClientes jceClientes, JcePublicadoras jcePublicadoras, String jceNumpedido, double jceTotal) {
       this.jceIdvendas = jceIdvendas;
       this.jceClientes = jceClientes;
       this.jcePublicadoras = jcePublicadoras;
       this.jceNumpedido = jceNumpedido;
       this.jceTotal = jceTotal;
    }
   
     @Id 

    
    @Column(name="jce_idvendas", unique=true, nullable=false)
    public int getJceIdvendas() {
        return this.jceIdvendas;
    }
    
    public void setJceIdvendas(int jceIdvendas) {
        this.jceIdvendas = jceIdvendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_clientes", nullable=false)
    public JceClientes getJceClientes() {
        return this.jceClientes;
    }
    
    public void setJceClientes(JceClientes jceClientes) {
        this.jceClientes = jceClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jce_publicadoras", nullable=false)
    public JcePublicadoras getJcePublicadoras() {
        return this.jcePublicadoras;
    }
    
    public void setJcePublicadoras(JcePublicadoras jcePublicadoras) {
        this.jcePublicadoras = jcePublicadoras;
    }

    
    @Column(name="jce_numpedido", nullable=false, length=10)
    public String getJceNumpedido() {
        return this.jceNumpedido;
    }
    
    public void setJceNumpedido(String jceNumpedido) {
        this.jceNumpedido = jceNumpedido;
    }

    
    @Column(name="jce_total", nullable=false, precision=22, scale=0)
    public double getJceTotal() {
        return this.jceTotal;
    }
    
    public void setJceTotal(double jceTotal) {
        this.jceTotal = jceTotal;
    }




}


